### PR TITLE
Cleanup errors, warnings and hints from the analyzer and from strong mode

### PR DESCRIPTION
**Pull request by jwren**

### CODE REVIEW

**Comment by hterkelsen** [comment]
Please also update the pub version.
@rkirov can you please look at this?

**Comment by rkirov** [comment]
LGTM, bump the version and I will merge and push to pub.

**Comment by jwren** [comment]
Version bumped to 0.0.2

**Comment by jwren** [comment]
Ping.

**Comment by rkirov** [comment]
merged.

**Pull request closed without merging**
